/*
 * This file is generated by jOOQ.
 */
package jooq.human.tables.records;


import javax.annotation.Generated;

import jooq.human.tables.Address1;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address1Record extends UpdatableRecordImpl<Address1Record> implements Record3<Long, String, Long> {

    private static final long serialVersionUID = -186387399;

    /**
     * Setter for <code>human.address1.address_id</code>.
     */
    public void setAddressId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>human.address1.address_id</code>.
     */
    public Long getAddressId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>human.address1.address1</code>.
     */
    public void setAddress1(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>human.address1.address1</code>.
     */
    public String getAddress1() {
        return (String) get(1);
    }

    /**
     * Setter for <code>human.address1.people_id</code>.
     */
    public void setPeopleId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>human.address1.people_id</code>.
     */
    public Long getPeopleId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Address1.ADDRESS1.ADDRESS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Address1.ADDRESS1.ADDRESS1_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Address1.ADDRESS1.PEOPLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getAddressId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAddress1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getPeopleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getAddressId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAddress1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getPeopleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Address1Record value1(Long value) {
        setAddressId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Address1Record value2(String value) {
        setAddress1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Address1Record value3(Long value) {
        setPeopleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Address1Record values(Long value1, String value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Address1Record
     */
    public Address1Record() {
        super(Address1.ADDRESS1);
    }

    /**
     * Create a detached, initialised Address1Record
     */
    public Address1Record(Long addressId, String address1, Long peopleId) {
        super(Address1.ADDRESS1);

        set(0, addressId);
        set(1, address1);
        set(2, peopleId);
    }
}
