/*
 * This file is generated by jOOQ.
 */
package jooq.human;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.DefaultCatalog;
import jooq.human.tables.Address1;
import jooq.human.tables.People;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Human extends SchemaImpl {

    private static final long serialVersionUID = -708797882;

    /**
     * The reference instance of <code>human</code>
     */
    public static final Human HUMAN = new Human();

    /**
     * The table <code>human.address1</code>.
     */
    public final Address1 ADDRESS1 = jooq.human.tables.Address1.ADDRESS1;

    /**
     * The table <code>human.people</code>.
     */
    public final People PEOPLE = jooq.human.tables.People.PEOPLE;

    /**
     * No further instances allowed
     */
    private Human() {
        super("human", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Address1.ADDRESS1,
            People.PEOPLE);
    }
}
