/*
 * This file is generated by jOOQ.
 */
package jooq.human;


import javax.annotation.Generated;

import jooq.human.tables.Address1;
import jooq.human.tables.People;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>human</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADDRESS1_PRIMARY = Indexes0.ADDRESS1_PRIMARY;
    public static final Index PEOPLE_PRIMARY = Indexes0.PEOPLE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADDRESS1_PRIMARY = Internal.createIndex("PRIMARY", Address1.ADDRESS1, new OrderField[] { Address1.ADDRESS1.ADDRESS_ID }, true);
        public static Index PEOPLE_PRIMARY = Internal.createIndex("PRIMARY", People.PEOPLE, new OrderField[] { People.PEOPLE.PERSON_ID }, true);
    }
}
