/*
 * This file is generated by jOOQ.
 */
package jooq.human;


import javax.annotation.Generated;

import jooq.human.tables.Address1;
import jooq.human.tables.People;


/**
 * Convenience access to all tables in human
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>human.address1</code>.
     */
    public static final Address1 ADDRESS1 = jooq.human.tables.Address1.ADDRESS1;

    /**
     * The table <code>human.people</code>.
     */
    public static final People PEOPLE = jooq.human.tables.People.PEOPLE;
}
